[package]
name = "common"
version = "0.1.0"
edition = "2021"
authors = ["Garunetra Labs"]
description = "Common utility tools for Garunetra"
license = "MIT"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
