[package]
name = "netravue"
version = "0.1.0"
edition = "2021"
authors = ["Garunetra Labs"]
description = "Visualization server and frontend integration for Garunetra"
license = "MIT"

[dependencies]
